# Built with Jekyll 3.6.0

# Setup
title:               Nicholas Sanders
#tagline:             'a jekyll theme for minimal editions'
#description:         'Ed is a Jekyll theme designed for textual editors based on minimal computing principles, and focused on legibility and flexibility.'
#url:                 'http://minicomp.github.io'
baseurl:             '/ed'




# Remote Theme
# (Used only for GitHub deployments)
# See https://help.github.com/en/articles/adding-a-jekyll-theme-to-your-github-pages-site
remote_theme: minicomp/ed
